### ISSUE TITLE
dubbo_unauthorized 有误报

### ISSUE THREAD

**Issue by kaka77** [chainreactors/gogo#38]
漏扫信息：
 tcp://xx.xx.xx.xx.xx:20880                    focus:dubbo-remote       [tcp] Unsupported c [ high: dubbo_unauthorized ]

验证信息：
Trying xx.xx.xx.xx.xx...
Connected to xx.xx.xx.xx.xx.
Escape character is '^]'.
ls
Command: ls disabled for security reasons, please enable support by listing the commands through 'telnet'

**Comment by M09Ic** [comment]
当前的dubbo规则为:

```
- name: dubbo-remote
  focus: true
  default_port:
    - dubbo
  protocol: tcp
  rule:
    - regexps:
        vuln:
          - dubbo
      vuln: dubbo_unauthorized
```

应该是返回值中出现了dubbo字段, 后续会改进该指纹
