### ISSUE TITLE
疑似bug问题

### ISSUE THREAD

**Issue by Layjb** [chainreactors/gogo#50]
我在测试期间发现的一个问题
./gogo -i x.x.x.x -p 8848 --exploit-name=nacos-default-login是有漏洞输出的
[+] http://x.x.x.126:8848                           [200] Nacos [ high: nacos-default-login payloads: password:nacos  username:nacos  ]  

但是./gogo -i x.x.x.126 -p 8848 -ev是没有漏洞输出的，换而言之只有指定了漏洞才会有输出，我暂时没有发现这是什么原因，如果需要目标ip进行测试，请与我联系

**Comment by Layjb** [comment]
貌似找到了原因，是因为没有匹配到指纹,我瞅瞅源码看看怎么优化

**Comment by M09Ic** [comment]
title位于body之中， 用body匹配都可以匹配到

**Comment by M09Ic** [comment]
经过测试， 确实存在部分nacos版本无法识别的问题。 

![image](https://github.com/chainreactors/gogo/assets/29176200/c6c3f74c-4cdf-4a30-b378-68dc3070a20d)

现在指纹修正为
```
- name: nacos
  focus: true
  rule:
    - regexps:
        body:
          - <title>Nacos</title>
      send_data: /nacos/
```

修正后结果
![image](https://github.com/chainreactors/gogo/assets/29176200/0ee3cb68-78c0-4842-8657-ebc5c279fbd4)

将于下个release一起发布
