### ISSUE TITLE
可以通过yaml文件加载poc吗？

### ISSUE THREAD

**Issue by lovelyjuice** [chainreactors/gogo#93]
比如--poc xxx.yaml
我这里有很多poc，但是打包进去会反序列化错误（generate的时候不会报错，但是扫描的时候会报错）
```
[-] neutron config load FAIL!, json: cannot unmarshal number into Go struct field Request.http.headers of type string
```
其中一个错误的原因：下面的判断条件nuclei是可以解析的，但是转换成json就会无法识别是布尔变量还是字符串变量
```
  matchers:
  - type: word
    part: body
    words:
    - false
 ```
改成
```
  matchers:
  - type: word
    part: body
    words:
    - 'false'
 ```
之后就正常了，我现在想要找出哪些poc有问题，就得用二分法在几百个poc里面找。。。如果能用命令行加载poc，我可以批量检测是哪些poc不兼容
